### ISSUE TITLE
Can I help you with klipse-io_livedemo-monokai-v2?

### ISSUE THREAD

**Issue by viebel** [jauhl/jauhl.github.io#1]
Hi there,

I'm the author of klipse.

Can I help you with
https://jauhl.github.io/playgrounds/klipse-io_livedemo-monokai-v2.html ?

**Comment by jauhl** [comment]
Hey. 
Thanks for reaching out but i was actually just looking for a simple syntaxhighlighter and meanwhile settled for codemirror.

**Comment by viebel** [comment]
ok
